const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94753356130"
const SESSION_ID = "PRABATH-MD~jG41hSzY#OzV6J2FgpF1k8h0DRqYd3XQQGnvtfiDYczflZqYWTNc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
